# 端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thesis_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: thesis_system
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    # Druid特定配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件最大大小
      max-request-size: 200MB  # 单次请求总文件最大大小
      enabled: true  # 启用文件上传支持

  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      connect-timeout: 3000ms

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.laboratory.paper.entity
  configuration:
    map-underscore-to-camel-case: true

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒），-1 代表永久有效
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: false

# 打印日志
logging:
  level:
    root: warn      # 设置全局日志级别
  file:
    path: ./log     # 日志输出路径
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'  # 日志文件的格式
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'  # 控制台输出的日志格式

# 文件服务器
file-server:
  url: http://localhost:8090

# 安全配置
safety:
  sm2:
    global: 'sm2:keypair:global'  # sm2公钥在redis存储名

# 登录相关配置
login:
  remember:
    redis:
      key:
        prefix: 'login:remember:'  # 记住密码在redis中前缀
  captcha:
    redis:
      key:
        prefix: 'login:captcha:'

# 文件配置
file:
  upload-path: 'E:/file_system/thesis_management_system'

# deepseek配置
deepseek:
  api:
    type: 'qwen'    # 指定类型，deepseek或者qwen
#    url: 'https://api.deepseek.com'
#    key: 'sk-81f09f5379744ee28630f245d70a107f'
#    model: 'deepseek-chat'
    url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
    key: 'sk-6a65b87736214bd3b70558cddce5d026'
    model: 'qwen3-max'